name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set permissions for gradlew
        run: chmod +x ./gradlew  # Setze die Berechtigungen für das Gradle Wrapper-Skript

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker images with Docker Compose
        run: docker-compose build

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - name: Wait for your application to be ready
        run: |
          echo "Warte 30 Sekunden, bis die Anwendung bereit ist..."
          sleep 30
          # Optional: Überprüfen, ob die Anwendung bereit ist
          for i in {1..10}; do
            if curl -s http://localhost:7979/health; then
              echo "Anwendung ist bereit."
              break
            fi
            echo "Warte auf die Anwendung..."
            sleep 10
          done

      - name: Test your application against assessment
        run: |
          response=$(curl -X POST http://localhost:8080/v1/result -d '{}')
          echo "Assessment Response: $response"
          if [[ "$response" == *"expecting to see 75 customers but found 0"* ]]; then
            echo "Assessment Test fehlgeschlagen: $response"
            exit 1
          fi

      - name: Shut down Docker Compose services
        run: docker-compose down
