name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set permissions for gradlew
        run: chmod +x ./gradlew  # Setze die Berechtigungen für das Gradle Wrapper-Skript

      - name: Build with Gradle
        run: ./gradlew build

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images with Docker Compose
        run: docker-compose up --build

      - name: Wait for the services to be ready
        run: |
          echo "Warte auf den Assessment-Service, bis er bereit ist..."
          for i in {1..10}; do
              if curl -s http://localhost:8080/v1/dataset; then
                echo "Assessment-Service ist bereit."
                break
              fi
              echo "Warte auf den Assessment-Service..."
              sleep 10
          done

          echo "Warte auf den List-Service, bis er bereit ist..."
          for i in {1..10}; do
              if curl -s http://localhost:7979/getCustomers; then
                echo "List-Service ist bereit."
                break
              fi
              echo "Warte auf den List-Service..."
              sleep 10
          done

      - name: Test your application against assessment
        run: |
          echo "Executing GET request..."
          response_get=$(curl -s http://localhost:7979/getCustomers)  # Führe GET-Anfrage aus
          echo "GET Response: $response_get"  # Ausgabe der GET-Antwort
          
          echo "Executing POST request..."
          response_post=$(curl -X POST -s http://localhost:7979/postCustomerData -d '{}')  # Führe POST-Anfrage aus
          echo "POST Response: $response_post"  # Ausgabe der POST-Antwort

          # Hier die Bedingung anpassen, um die Ausgabe zu überprüfen
          if [[ "$response_post" == *"expecting to see 75 customers but found 0"* ]]; then
            echo "Assessment Test fehlgeschlagen: $response_post"
            exit 1
          fi

      - name: Shut down Docker Compose services
        run: docker-compose down
