name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set permissions for gradlew
        run: chmod +x ./gradlew  # Set the permissions for the Gradle Wrapper script

      - name: Build with Gradle
        run: ./gradlew build

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start your application and services defined in docker-compose.yml
        run: |
          # Build and start your application and services
          docker-compose up -d --build  # Start services in detached mode and build images if necessary

      - name: Wait for your application to start
        run: |
          echo "Waiting 10 seconds for the application to be ready..."
          sleep 10

      - name: Test your application against assessment
        run: |
          # Test your application by interacting with the assessment image
          response_post=$(curl -s -X POST http://localhost:8080/v1/result -d '{}')
          if [[ "$response_post" == *"expecting to see 75 customers but found 0"* ]]; then
            echo "Assessment Test failed: $response_post"
            exit 1
          fi

      - name: Shut down Docker containers
        run: |
          # Stop and remove all containers defined in docker-compose.yml
          docker-compose down
