name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set permissions for gradlew
        run: chmod +x ./gradlew  # Setze die Berechtigungen für das Gradle Wrapper-Skript

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build your application Docker image
        run: |
          docker build -t your-app-image -f Dockerfile .

      - name: Run your application
        run: |
          docker run -d --name your-app -p 7979:7979 your-app-image

      - name: Wait for your application to start
        run: |
          echo "Warte 10 Sekunden, bis die Anwendung bereit ist..."
          sleep 10
          # Alternativ kannst du den Status mit curl überprüfen
          for i in {1..10}; do
            if curl -s http://localhost:7979/health; then
              echo "Anwendung ist bereit."
              break
            fi
            echo "Warte auf die Anwendung..."
            sleep 10
          done

      - name: Run Assessment Docker Image
        run: |
          docker run -d --name assessment -p 8080:8080 mrksdh/assessment

      - name: Wait for assessment to be ready
        run: |
          echo "Warte 10 Sekunden, bis das Assessment bereit ist..."
          sleep 10

      - name: Test your application against assessment
        run: |
          response=$(curl -X POST http://localhost:8080/v1/result -d '{}')
          echo "Assessment Response: $response"
          if [[ "$response" == *"expecting to see 75 customers but found 0"* ]]; then
            echo "Assessment Test fehlgeschlagen: $response"
            exit 1
          fi

      - name: Shut down your application
        run: docker stop your-app && docker rm your-app

      - name: Shut down the assessment container
        run: docker stop assessment && docker rm assessment
