name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # Verwendung von Temurin als JDK-Distribution
        java-version: '17'

    - name: Set execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Test the application
      run: |
        sleep 10 # Warte, bis die Anwendung gestartet ist
        curl -X POST http://localhost:8080/v1/result -d '{}' # Hier deine Tests durchführen

    - name: Shut down Docker Compose
      run: docker-compose down
