name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set permissions for gradlew
        run: chmod +x ./gradlew  # Setze die Berechtigungen für das Gradle Wrapper-Skript

      - name: Build with Gradle
        run: ./gradlew build

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images with Docker Compose
        run: docker-compose build

      - name: Start assessment service with Docker Compose
        run: docker-compose up -d assessment

      - name: Wait for assessment service to be ready
        run: |
          echo "Warte auf den Assessment-Service, bis er bereit ist..."
          for i in {1..10}; do
              if curl -s http://localhost:8080/v1/dataset; then
                echo "Assessment-Service ist bereit."
                break
              fi
              echo "Warte auf den Assessment-Service..."
              sleep 10
          done

      - name: Start list service with Docker Compose
        run: docker-compose up -d list

      - name: Wait for your list application to be ready
        run: |
          echo "Warte auf den List-Service, bis er bereit ist..."
          for i in {1..10}; do
              if curl -s http://localhost:7979/getCustomers; then
                echo "List-Service ist bereit."
                break
              fi
              echo "Warte auf den List-Service..."
              sleep 10
          done

      - name: Test your application against assessment
        run: |
          response=$(curl -X POST http://localhost:8080/v1/result -d '{}')
          echo "Assessment Response: $response"
          if [[ "$response" == *"expecting to see 75 customers but found 0"* ]]; then
            echo "Assessment Test fehlgeschlagen: $response"
            exit 1
          fi

      - name: Shut down Docker Compose services
        run: docker-compose down
